name: Automatic Pull Request

env:
  GH_CLI_PAT: ${{ secrets.GH_CLI_PAT }}
  GH_CLI_PR_JSON_FIELDS: '[
    "closed",
    "headRefName",
    "id",
    "mergeable",
    "mergeStateStatus",
    "number",
    "state",
    "title",
    "url"
  ]'

  repository_owner: hwwilliams
  repository_name: automatic-pull-request

on:
  push:
    branches: [main]

jobs:
  auto-pr:
    name: Automatic Pull Request
    if: success() && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Get Date
      #   id: date
      #   run: |
      #     date=$(date +'%Y-%m-%d')
      #     echo "date=$date" >> $GITHUB_OUTPUT

      - name: Check for Existing Pull Requests
        shell: pwsh
        run: |
          $JsonFieldsCsv = (${{ env.GH_CLI_PR_JSON_FIELDS }} | ConvertFrom-Json) -join ","
          $RepoFullName="${{ env.repository_owner }}/${{ env.repository_name }}"

          echo "Checking for existing pull requests on repository '$REPO_FULL_NAME'"
          $RepoPRsJson = gh pr -R "$RepoFullName" list --json "$JsonFieldsCsv"
          $RepoPRs = $RepoPRsJson | ConvertFrom-Json -AsHashtable
          $OpenRepoPRs = $RepoPRs.Where({ $PSItem.state -eq "OPEN" })

          if ($OpenRepoPRs.Count -gt 0)
          {
            $OpenRepoPRs
          }
          else
          {
            Write-Warning "Found 0 pull requests for repository '$RepoFullName'"
          }
        env:
          GH_TOKEN: ${{ env.GH_CLI_PAT }}
