name: Automatic Pull Request

env:
  GH_CLI_PAT: ${{ secrets.GH_CLI_PAT }}

  repository_owner: hwwilliams
  repository_name: automatic-pull-request

on:
  push:
    branches: [main]

jobs:
  auto-pr:
    name: Automatic Pull Request
    if: success() && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Date
        id: date
        run: |
          date=$(date +'%Y-%m-%d')
          echo "date=$date" >> $GITHUB_OUTPUT

      - name: Check for Existing Pull Requests
        run: |
          JSON_FIELDS=("closed" "headRefName" "id" "mergeable" "mergeStateStatus" "number" "state" "title" "url")
          JSON_FIELDS_CSV=$(IFS=, ; echo "${JSON_FIELDS[*]}")

          REPO_FULL_NAME="${{ env.repository_owner }}/${{ env.repository_name }}"
          echo "Checking for existing pull requests on repository '$REPO_FULL_NAME'"

          REPO_PR=$(gh pr -R "$REPO_FULL_NAME" list --json "$JSON_FIELDS_CSV")
          if [[ "$REPO_PR" == "no open pull requests"*  ]]; then
            echo "Found 0 pull requests for repository '$REPO_FULL_NAME'"
          else
            echo "$REPO_PR"
          fi
        env:
          GH_TOKEN: ${{ env.GH_CLI_PAT }}
