name: Automatic Pull Request

env:
  GH_CLI_PAT: ${{ SECRETS.GH_CLI_PAT }}
  GH_CLI_PR_JSON_FIELDS: closed,headRefName,id,mergeable,mergeStateStatus,number,state,title,url
  REPOSITORY_OWNER: HWWILLIAMS
  REPOSITORY_NAME: automatic-pull-request

on:
  push:
    branches: [main]

jobs:
  auto-pr:
    name: Automatic Pull Request
    if: success() && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Get Date
      #   id: date
      #   run: |
      #     date=$(date +'%Y-%m-%d')
      #     echo "date=$date" >> $GITHUB_OUTPUT

      - name: Check for Existing Pull Requests
        shell: pwsh
        run: |
          $RepoFullName="${{ env.REPOSITORY_OWNER }}/${{ env.REPOSITORY_NAME }}"

          echo "Checking for existing pull requests on repository '$RepoFullName'"
          $RepoPRsJson = gh pr -R "$RepoFullName" list --json "${{ env.GH_CLI_PR_JSON_FIELDS }}"

          $OpenRepoPRs = ($RepoPRsJson | ConvertFrom-Json -AsHashtable).Where({ $PSItem.state -eq "OPEN" })
          if ($OpenRepoPRs.Count -ge 2)
          {
            Write-Error "Found $($OpenRepoPRs.Count) release PRs open"
            $OpenRepoPRs
          }
          elseif ($OpenRepoPRs.Count -eq 1)
          {
            Write-Output "Found release PR"
            $OpenRepoPRs

            echo "existing_pull_request=true" >> $env:GITHUB_OUTPUT
          }
          else
          {
            Write-Warning "Found 0 pull requests for repository '$RepoFullName'"

            echo "existing_pull_request=false" >> $env:GITHUB_OUTPUT
          }
        env:
          GH_TOKEN: ${{ env.GH_CLI_PAT }}
