name: Automatic Pull Request

env:
  GH_CLI_PAT: ${{ SECRETS.GH_CLI_PAT }}
  GH_CLI_PR_JSON_FIELDS: CLOSED,HEADREFNAME,ID,MERGEABLE,MERGESTATESTATUS,NUMBER,STATE,TITLE,URL
  REPOSITORY_OWNER: HWWILLIAMS
  REPOSITORY_NAME: automatic-pull-request

on:
  push:
    branches: [main]

jobs:
  auto-pr:
    name: Automatic Pull Request
    if: success() && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Get Date
      #   id: date
      #   run: |
      #     date=$(date +'%Y-%m-%d')
      #     echo "date=$date" >> $GITHUB_OUTPUT

      - name: Check for Existing Pull Requests
        shell: pwsh
        run: |
          $RepoFullName="${{ env.REPOSITORY_OWNER }}/${{ env.REPOSITORY_NAME }}"

          echo "Checking for existing pull requests on repository '$REPO_FULL_NAME'"
          $RepoPRsJson = gh pr -R "$RepoFullName" list --json "${{ env.GH_CLI_PR_JSON_FIELDS }}"
          $RepoPRs = $RepoPRsJson | ConvertFrom-Json -AsHashtable
          $OpenRepoPRs = $RepoPRs.Where({ $PSItem.state -eq "OPEN" })

          if ($OpenRepoPRs.Count -gt 0)
          {
            $OpenRepoPRs
          }
          else
          {
            Write-Warning "Found 0 pull requests for repository '$RepoFullName'"
          }
        env:
          GH_TOKEN: ${{ env.GH_CLI_PAT }}
